import json

# 定义每个 comic 的模板
def create_comic_entry(comic_id):
    return {
        "name": "待更新",
        "author": "",
        "type": 769844263,
        "tags": [""],
        "id": str(comic_id),
        "coverPath": ""
    }

# 读取venera_input_numbers.txt 并生成 comics 列表
comics = []
with open("venera_input_numbers.txt", "r", encoding="utf-8") as file:
    for line in file:
        comic_id = line.strip()
        if comic_id:  # 忽略空行
            comics.append(create_comic_entry(comic_id))

# 构建最终的 JSON 结构
output_data = {
    "info": "Generated by Venera",
    "name": "已导入",
    "comics": comics
}

# 写入到 venera_input.json 文件
with open("venera_input.json", "w", encoding="utf-8") as outfile:
    json.dump(output_data, outfile, ensure_ascii=False, indent=4)

print("JSON 文件已生成：venera_input.json")